name: Add CNAME file to docs

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      run: | 
        touch docs/CNAME
        echo 'mocktailapp.io' > ~/docs/CNAME
