name: Add CNAME file to docs

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create CNAME file
#        run: printf 'mocktailapp.io' > CNAME
        run: printf 'Hello world' > ~docs/CNAME
